import { Button, Center, Checkbox, Container, PasswordInput, Space, Text, TextInput, Title } from '@mantine/core'
import Head from 'next/head';
import Image from 'next/image';
import { useForm } from '@mantine/hooks';
import { supabase } from '../frameworks/supabase';
import { useRouter } from 'next/router';
import React from 'react'
import { useNotifications } from '@mantine/notifications';

export default function Home() {
  const router = useRouter();
  const [loading, setLoading] = React.useState(false);
  const notifications = useNotifications()
  
  const form = useForm({
    initialValues: {
      email: '',
      password: '',
    },

    validationRules: {
      email: (value) => /^\S+@\S+$/.test(value),
    },
  });

  const onSubmit = async (data) => {
      setLoading(true)
      let res = await supabase.auth.signIn(data)
      console.log(res)
      if(res?.user?.role == 'supabase_admin'){
        router.push('/dashboard')
      }
      else{
        notifications.showNotification({
          message:res?.error?.message
        })
      }
      setLoading(false)
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center style={{ width: "100vw", height: "100vh" }}>
        <Container>
        <Title order={1}>Admin Ubid</Title>
          <form onSubmit={form.onSubmit(onSubmit)}>
            <TextInput
              required
              label="Email"
              placeholder="your@email.com"
              {...form.getInputProps('email')}
            />
            <PasswordInput
              required
              label="Password"
              placeholder=""
              
              {...form.getInputProps('password')}
            />
            <Space h="sm" />


            <Button loading={loading} type="submit">Submit</Button>
          </form>

        </Container>
      </Center>


    </div>
  )
}
